# docker-compose-dev.yaml
services:
  web:
    container_name: openstack_django
    build: .
    command: ["uvicorn", "openstack.asgi:application", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env
    networks:
      - openstack-net

  db:
    container_name: openstack_postgres
    image: postgres:${PG_VERSION:-16}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - openstack-net

  redis:
    container_name: openstack_redis
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - openstack-net

  celery:
    container_name: openstack_celery
    build: .
    command: ["celery", "-A", "openstack", "worker", "--loglevel=INFO"]
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    env_file:
      - ./.env
    networks:
      - openstack-net

volumes:
  postgres_data:

networks:
  openstack-net: